# Numpy Class 1

In [1]:
a = [1,2,3,4,5,6,7,8,9]

In [2]:
b = []
for num in a:
    b.append(num*2)
    
b

[2, 4, 6, 8, 10, 12, 14, 16, 18]

In [3]:
import numpy as np

In [4]:
a = np.array([1,2,3,4,5,6])

In [5]:
a

array([1, 2, 3, 4, 5, 6])

In [6]:
type(a)

numpy.ndarray

In [7]:
2*a

array([ 2,  4,  6,  8, 10, 12])

In [8]:
data = np.random.randn(2,3)

In [9]:
data

array([[-1.40360109, -0.27356587, -0.85617161],
       [-0.51374653,  0.28381372,  0.24622909]])

In [10]:
data = np.random.randn(2,3)

In [11]:
data

array([[ 0.04078967,  1.79492487,  0.56258894],
       [ 1.01179065, -0.24021629, -0.42277401]])

In [12]:
data2 = np.arange(10)

In [13]:
data2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
data2.ndim

1

In [15]:
data.ndim

2

In [16]:
data.shape

(2, 3)

In [17]:
data2.shape

(10,)

In [18]:
b = np.array([[100]])

In [19]:
b.ndim

2

In [20]:
b.shape

(1, 1)

In [21]:
_3d = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [22]:
_3d.ndim

3

In [24]:
_3d

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [33]:
threeD = np.arange(64).reshape(4,4,4)

In [34]:
threeD

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [35]:
threeD2 = np.arange(60).reshape(5,3,4)

In [36]:
threeD2

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]],

       [[36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59]]])

In [37]:
threeD3 = np.arange(30).reshape(2,5,3)

In [38]:
threeD3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [39]:
threeD.ndim

3

In [111]:
m1 = np.arange(12).reshape(4,3)
m2 = np.array([[1,2,3],[4,5,6],[7,8,9],[9,8,7]])

In [112]:
m1.shape == m2.shape

True

In [113]:
m1.ndim

2

In [114]:
m1.ndim

2

In [115]:
m1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [116]:
m2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [9, 8, 7]])

In [117]:
m1-m2

array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1],
       [ 0,  2,  4]])

In [118]:
m1+m2

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [18, 18, 18]])

In [119]:
m1*m2      #'*' means mirror multiplication

array([[ 0,  2,  6],
       [12, 20, 30],
       [42, 56, 72],
       [81, 80, 77]])

In [120]:
m1/m2

array([[0.        , 0.5       , 0.66666667],
       [0.75      , 0.8       , 0.83333333],
       [0.85714286, 0.875     , 0.88888889],
       [1.        , 1.25      , 1.57142857]])

In [121]:
m1.shape

(4, 3)

In [122]:
m2.shape

(4, 3)

In [123]:
m1@m2     #'@' means matrix multiplication

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)

In [126]:
m3 = m2.reshape(3,4)

In [127]:
m3.shape

(3, 4)

In [132]:
#Method 1 of matrix multiplication
print(m1.shape)
print(m3.shape)
m1@m3

(4, 3)
(3, 4)


array([[ 23,  24,  23,  22],
       [ 68,  75,  77,  79],
       [113, 126, 131, 136],
       [158, 177, 185, 193]])

In [133]:
#Method 2 of matrix multiplication
np.dot(m1,m3)

array([[ 23,  24,  23,  22],
       [ 68,  75,  77,  79],
       [113, 126, 131, 136],
       [158, 177, 185, 193]])

In [134]:
#Method 3 of matrix multiplication
m1.dot(m3)

array([[ 23,  24,  23,  22],
       [ 68,  75,  77,  79],
       [113, 126, 131, 136],
       [158, 177, 185, 193]])

In [136]:
a = np.array([33,44,55])

In [137]:
a.dtype

dtype('int32')

In [139]:
a = np.array([33,44,55], dtype = 'float32')

In [140]:
a

array([33., 44., 55.], dtype=float32)

In [141]:
a = np.array([33,44,55], dtype = np.float32)

In [142]:
a

array([33., 44., 55.], dtype=float32)

In [146]:
b = np.asarray(a,"int32")

In [147]:
b

array([33, 44, 55])

In [148]:
b.dtype

dtype('int32')

In [149]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [150]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [151]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [152]:
np.empty((3,3))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 6.04736351e-321],
       [1.78019354e-306, 1.37962388e-306, 2.56761491e-312]])

In [165]:
np.empty(4)

array([2., 2., 2., 2.])

In [160]:
np.ones((2,2))*2

array([[2., 2.],
       [2., 2.]])

In [167]:
ba = np.full((3,3),2)

In [169]:
ba

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [170]:
ja = np.ones_like(ba)

In [171]:
ja

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [173]:
alist = [1,2,3,4,5,6,7,8]

In [174]:
alist[4]     #indexing

5

In [175]:
type(alist[2:4])

list

In [176]:
td = np.arange(36).reshape(6,6)

In [177]:
td

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [178]:
#td[r,c]
#td[--, --]
a = td[2:4, 2:4]

In [179]:
a

array([[14, 15],
       [20, 21]])

In [181]:
td[2][3]

15

In [182]:
td

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])